insert into station values('KVZ','kavali');
insert into station values('MAS','chennai central');
insert into station values('NLR','nellore');
insert into station values('WL','warangal');
insert into station values('SC','secunderabad');
insert into station values('OGL','ongole');
insert into station values('BZA','vijayawada');
insert into station values('GDR','gudur junction');
insert into station values('RJY','rajamundry');
insert into station values('VSKP','vishakhapatnam');
insert into station values('GNT','Guntur');
insert into station values('KRNT','kurnool');
insert into station values('GWD','gadwal junction');
insert into station values('GY','gooty junction');